### ISSUE TITLE
First Simple Enemy AI

### ISSUE THREAD

**Issue by CezarRC** [CezarRC/PJ-MP#13]
First Simple Enemy AI
Este Backlog item implica na criação do primeiro inimigo base, com os scripts de:
Vida, Perseguir GameObjects(Para reaproveitamento futuro nos inimigos com focos específicos), Tratar Colisões, Dropar Scraps.

**Comment by GFritter** [comment]
created the enemy basic_AI, 
Dealing Damage and Scrap Dropping not yet implemented
